// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateImageToImage(arg1) {
  return window['go']['main']['App']['GenerateImageToImage'](arg1);
}

export function GenerateInpaint(arg1) {
  return window['go']['main']['App']['GenerateInpaint'](arg1);
}

export function GenerateTextToImage(arg1) {
  return window['go']['main']['App']['GenerateTextToImage'](arg1);
}

export function GenerateVideo(arg1) {
  return window['go']['main']['App']['GenerateVideo'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetImageModels() {
  return window['go']['main']['App']['GetImageModels']();
}

export function GetVideoModels() {
  return window['go']['main']['App']['GetVideoModels']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function OpenLocalFile(arg1) {
  return window['go']['main']['App']['OpenLocalFile'](arg1);
}

export function OpenOutputDir() {
  return window['go']['main']['App']['OpenOutputDir']();
}

export function PollImageTask(arg1) {
  return window['go']['main']['App']['PollImageTask'](arg1);
}

export function PollVideoTask(arg1) {
  return window['go']['main']['App']['PollVideoTask'](arg1);
}

export function RegConfig() {
  return window['go']['main']['App']['RegConfig']();
}

export function RegGptBatchDelete(arg1) {
  return window['go']['main']['App']['RegGptBatchDelete'](arg1);
}

export function RegGptBatchRefresh(arg1) {
  return window['go']['main']['App']['RegGptBatchRefresh'](arg1);
}

export function RegGptDelete(arg1) {
  return window['go']['main']['App']['RegGptDelete'](arg1);
}

export function RegGptDeleteInvalid() {
  return window['go']['main']['App']['RegGptDeleteInvalid']();
}

export function RegGptDetail(arg1) {
  return window['go']['main']['App']['RegGptDetail'](arg1);
}

export function RegGptExport(arg1, arg2) {
  return window['go']['main']['App']['RegGptExport'](arg1, arg2);
}

export function RegGptImport(arg1) {
  return window['go']['main']['App']['RegGptImport'](arg1);
}

export function RegGptList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegGptList'](arg1, arg2, arg3, arg4);
}

export function RegGptQuota(arg1) {
  return window['go']['main']['App']['RegGptQuota'](arg1);
}

export function RegGptRefresh(arg1) {
  return window['go']['main']['App']['RegGptRefresh'](arg1);
}

export function RegGptStats() {
  return window['go']['main']['App']['RegGptStats']();
}

export function RegGptUpdate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RegGptUpdate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RegMailBatchDelete(arg1) {
  return window['go']['main']['App']['RegMailBatchDelete'](arg1);
}

export function RegMailClearAll() {
  return window['go']['main']['App']['RegMailClearAll']();
}

export function RegMailDelete(arg1) {
  return window['go']['main']['App']['RegMailDelete'](arg1);
}

export function RegMailDeleteByStatus(arg1) {
  return window['go']['main']['App']['RegMailDeleteByStatus'](arg1);
}

export function RegMailFetch(arg1, arg2) {
  return window['go']['main']['App']['RegMailFetch'](arg1, arg2);
}

export function RegMailImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegMailImport'](arg1, arg2, arg3);
}

export function RegMailList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegMailList'](arg1, arg2, arg3, arg4, arg5);
}

export function RegMailReset(arg1) {
  return window['go']['main']['App']['RegMailReset'](arg1);
}

export function RegMailStats() {
  return window['go']['main']['App']['RegMailStats']();
}

export function RegMailUpdate(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RegMailUpdate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RegPoolGenModels() {
  return window['go']['main']['App']['RegPoolGenModels']();
}

export function RegPoolGenerate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RegPoolGenerate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RegPoolGenerateFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegPoolGenerateFile'](arg1, arg2, arg3, arg4, arg5);
}

export function RegSetConfig(arg1) {
  return window['go']['main']['App']['RegSetConfig'](arg1);
}

export function RegTaskCancel(arg1) {
  return window['go']['main']['App']['RegTaskCancel'](arg1);
}

export function RegTaskCreate(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegTaskCreate'](arg1, arg2, arg3);
}

export function RegTaskDelete(arg1) {
  return window['go']['main']['App']['RegTaskDelete'](arg1);
}

export function RegTaskList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegTaskList'](arg1, arg2, arg3, arg4, arg5);
}

export function RegTaskLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegTaskLogs'](arg1, arg2, arg3);
}

export function RegTaskPurge(arg1) {
  return window['go']['main']['App']['RegTaskPurge'](arg1);
}

export function RegTaskStats(arg1) {
  return window['go']['main']['App']['RegTaskStats'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['SaveRemoteFile'](arg1, arg2);
}
