// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dto} from '../models';
import {mailbox} from '../models';

export function GenerateImageToImage(arg1:main.GenerationRequest):Promise<main.GenerationResponse>;

export function GenerateInpaint(arg1:main.GenerationRequest):Promise<main.GenerationResponse>;

export function GenerateTextToImage(arg1:main.GenerationRequest):Promise<main.GenerationResponse>;

export function GenerateVideo(arg1:main.GenerationRequest):Promise<main.GenerationResponse>;

export function GetAppConfig():Promise<main.AppConfig>;

export function GetImageModels():Promise<Array<main.ImageModel>>;

export function GetVideoModels():Promise<Array<main.VideoModel>>;

export function LoadHistory():Promise<Array<main.HistoryItem>>;

export function OpenLocalFile(arg1:string):Promise<boolean>;

export function OpenOutputDir():Promise<boolean>;

export function PollImageTask(arg1:string):Promise<main.GenerationResponse>;

export function PollVideoTask(arg1:string):Promise<main.GenerationResponse>;

export function RegConfig():Promise<Record<string, string>>;

export function RegGptBatchDelete(arg1:Array<number>):Promise<number>;

export function RegGptBatchRefresh(arg1:Array<number>):Promise<dto.GptBatchRefreshResp>;

export function RegGptDelete(arg1:number):Promise<void>;

export function RegGptDeleteInvalid():Promise<number>;

export function RegGptDetail(arg1:number):Promise<dto.GptPoolDetailResp>;

export function RegGptExport(arg1:string,arg2:Array<number>):Promise<string>;

export function RegGptImport(arg1:string):Promise<dto.GptPoolImportResult>;

export function RegGptList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.GptPoolPage>;

export function RegGptQuota(arg1:number):Promise<dto.GptQuotaResp>;

export function RegGptRefresh(arg1:number):Promise<dto.GptRefreshResp>;

export function RegGptStats():Promise<dto.GptPoolStatsResp>;

export function RegGptUpdate(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:number):Promise<void>;

export function RegMailBatchDelete(arg1:Array<number>):Promise<number>;

export function RegMailClearAll():Promise<number>;

export function RegMailDelete(arg1:number):Promise<void>;

export function RegMailDeleteByStatus(arg1:string):Promise<number>;

export function RegMailFetch(arg1:number,arg2:number):Promise<Array<mailbox.MailMessage>>;

export function RegMailImport(arg1:string,arg2:string,arg3:string):Promise<dto.MailPoolImportResult>;

export function RegMailList(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.MailPoolPage>;

export function RegMailReset(arg1:Array<number>):Promise<number>;

export function RegMailStats():Promise<dto.MailPoolStatsResp>;

export function RegMailUpdate(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function RegPoolGenModels():Promise<Array<main.PoolGenModel>>;

export function RegPoolGenerate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:Array<string>,arg8:number,arg9:string):Promise<main.PoolGenResult>;

export function RegPoolGenerateFile(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:string):Promise<main.PoolFileResult>;

export function RegSetConfig(arg1:Record<string, string>):Promise<void>;

export function RegTaskCancel(arg1:number):Promise<void>;

export function RegTaskCreate(arg1:string,arg2:number,arg3:Record<string, any>):Promise<dto.RegisterTaskCreateResp>;

export function RegTaskDelete(arg1:number):Promise<void>;

export function RegTaskList(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.RegisterTaskPage>;

export function RegTaskLogs(arg1:number,arg2:string,arg3:number):Promise<Array<dto.RegisterTaskLogResp>>;

export function RegTaskPurge(arg1:string):Promise<number>;

export function RegTaskStats(arg1:string):Promise<dto.RegisterTaskStatsResp>;

export function SaveAppConfig(arg1:main.AppConfig):Promise<boolean>;

export function SaveHistory(arg1:main.HistoryItem):Promise<boolean>;

export function SaveImage(arg1:string,arg2:string):Promise<boolean>;

export function SaveRemoteFile(arg1:string,arg2:string):Promise<string>;
